spring:
  application:
    name: expense.tracker
  datasource:
    url: jdbc:postgresql://expensetracker-ademth11-159e.l.aivencloud.com:13224/defaultdb?ssl=require&user=avnadmin&password=AVNS_0zOD6zze132QSUS-jTC
    driver-class-name: org.postgresql.Driver
    username: avnadmin
    password: AVNS_0zOD6zze132QSUS-jTC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9999

